print("First, state of all your names")
a = str(input())
b = str(input())
c = str(input())
d = str(input())
print("Now, say the GPAs for each student")
w = float(input())
x = float(input())
y = float(input())
z = float(input())
average = str((w+x+y+z)/4)
print("The following students: ")
print(a)
print(b)
print(c)
print(d)
print("have an average GPA of " + average)

